export const T = {
  bg:"var(--surface)",
  panel:"var(--surface-raised)",
  border:"var(--line)",
  navy:"var(--surface-overlay)",
  navyLt:"var(--line)",
  gold:"var(--accent)",
  goldLt:"var(--accent-hover)",
  cream:"var(--text)",
  muted:"var(--text-muted)",
  danger:"var(--critical)",
  ok:"var(--success)",
  warn:"var(--warning)",
};


// CSS is injected by the build script — T and LOC_COLORS are defined before this block
export const css = `
/* THEME-TOKENS-START — generated, do not hand-edit */
/* Generated by tools/rollout_theme.mjs from the Finance Dashboard's
   styles.css. Change it THERE and re-run; editing here means the seven apps
   drift apart one value at a time, invisibly. */
:root,
:root[data-theme='light'] {
  color-scheme: light;

  --surface-sunken: #eef1f5;
  --surface: #f7f9fb;
  --surface-raised: #ffffff;
  --surface-overlay: #f0f3f7;
  /* #d6dee7 was the obvious choice and measured 1.29:1 against --surface —
     a hairline that effectively vanishes, which matters most on the dense
     Budget vs Actual and Trial Balance tables, and worse on a phone in
     sunlight. #c3cfdc gives 1.50:1 and still reads as a light rule. */
  --line: #c3cfdc;
  --text: #161b22;
  --text-muted: #5a6572;

  /* Darker semantic variants — the dark-mode ones are far too light to pass
     contrast on a white panel. */
  --success: #0f7a45;
  --warning: #9a5b00;
  --critical: #b42318;
  --informative: #175cd3;

  --accent: #4338ca;
  --accent-hover: #3730a3;
  --accent-active: #312e81;
  --accent-contrast: #ffffff;
  --accent-wash: rgba(67, 56, 202, 0.09);
  /* The panel accent (#4338CA) would be almost invisible on the navy rail,
     so the rail gets a lightened variant of the same client colour. */
  --accent-on-dark: #a5b4fc;
  --accent-on-dark-wash: rgba(165, 180, 252, 0.16);

  /* Softer and blue-tinted rather than neutral grey: a grey shadow on a
     light surface reads as dirt, a slightly cool one reads as depth. */
  --shadow-sm: 0 1px 2px rgba(22, 32, 46, 0.06), 0 1px 3px rgba(22, 32, 46, 0.08);
  --shadow-md: 0 2px 4px rgba(22, 32, 46, 0.04), 0 6px 16px rgba(22, 32, 46, 0.09);
  --shadow-lg: 0 8px 28px rgba(22, 32, 46, 0.13);

  --card-border: transparent;
  /* Lightened from #16202e (2026-09-06, Thijs). Every text token on the
     rail was re-measured against it rather than assumed — --sidebar-muted
     had to lift with it, see below. */
  --sidebar-bg: #233348;

  --series-1: #4338ca;
  --series-2: #0e7490;
  --series-3: #9a5b00;
  --series-4: #7e22ce;
  --series-5: #1d4ed8;
  --series-6: #b04a2f;

  /* Mode-independent: shape, type, and the legacy aliases that 194
     existing var() usages still read. These belong to the BASE block —
     left in the dark override they would simply not exist in light
     mode, and every aliased colour would fall back to nothing. */
  --radius-sm: 8px;
  --radius-md: 12px;
  --radius-lg: 16px;
  --sidebar-text: #e8edf4;
  /* Lifted with the rail. At #8b97a6 this fell to 4.32:1 on the new
     #233348 — under AA, and it is the colour the sidebar section labels
     and the footer use. */
  --sidebar-muted: #98a4b3;
  --sidebar-line: rgba(255, 255, 255, 0.1);
  /* ONE TYPEFACE. Three families was one and a half too many.
     Space Mono on money was the worse of the two: "R 348 997,39" set with
     wide letter-spacing and slab serifs reads as code, not currency. The
     only real argument for mono on numbers is column alignment, and Inter
     does that with font-variant-numeric: tabular-nums in a face that
     matches everything around it.
     Cormorant Garamond was a brand choice, not a product one. At 15–17px
     its thin strokes and small counters made headings read SOFTER than the
     body text beneath them — the opposite of a heading's job — and being
     the most identity-carrying thing on the page makes it exactly wrong for
     a white-label product, where the client's brand should arrive through
     the accent and the logo. It survives as --font-brand, used only where a
     human actually reads brand: the login screen and printed report heads. */
  --font-body: 'Inter', system-ui, -apple-system, sans-serif;
  --font-heading: 'Inter', system-ui, -apple-system, sans-serif;
  --font-numeric: 'Inter', system-ui, -apple-system, sans-serif;
  --font-brand: 'Cormorant Garamond', Georgia, serif;
  /* Kept so the existing var(--font-mono) call sites keep resolving. It is
     deliberately NOT monospace any more — the name is legacy, like --gold
     and --navy below. New code should say --font-numeric. */
  --font-mono: var(--font-numeric);
  --bg: var(--surface);
  --panel: var(--surface-raised);
  --panel-alt: var(--surface-overlay);
  --border: var(--line);
  --cream: var(--text);
  --muted: var(--text-muted);
  --navy: var(--surface-overlay);
  --navy-lt: var(--line);
  --gold: var(--accent);
  --gold-lt: var(--accent-hover);
  --ok: var(--success);
  --danger: var(--critical);
  --fuel-d: var(--informative);
  --fuel-p: var(--critical);
  --loc-zc: var(--series-1);
  --loc-ec: var(--series-2);
  --loc-sc: var(--series-3);
}

/* DARK IS THE OVERRIDE, LIGHT IS THE DEFAULT — deliberately.
   These blocks used to be the other way round, which meant the shipped
   default appearance depended on JavaScript running applyTheme() to set
   data-theme. When the branding wiring was reverted from an app, that
   attribute stopped being set and the app silently fell back to dark. A
   product's default look must not depend on a script succeeding. */
:root[data-theme='dark'] {
  color-scheme: dark;

  /* 1 — neutral base */
  --surface-sunken: #0f1216;
  --surface: #12161b;
  --surface-raised: #1a1f26;
  --surface-overlay: #222831;
  --line: #333c48;
  --text: #eef1f5;
  --text-muted: #9aa5b1;

  /* 2 — semantic, fixed */
  --success: #3dbe7a;
  --warning: #e8a33d;
  --critical: #f0736a;
  --informative: #63a8f0;

  /* 3 — accent. Overwritten at runtime by applyTheme(); this is only the
     fallback for a company with no accent set, and for the login screen
     which renders before any company is known. */
  --accent: #7c8cf8;
  --accent-hover: #93a0fa;
  --accent-active: #6675f0;
  --accent-contrast: #12161b;
  --accent-wash: rgba(124, 140, 248, 0.12);
  --accent-on-dark: #7c8cf8;
  --accent-on-dark-wash: rgba(124, 140, 248, 0.16);

  /* Elevation and shape. Previously both were hardcoded — one shadow value
     and 28 separate border-radius declarations — which meant "make the
     cards pop" was a find-and-replace rather than a setting. On a dark page
     lift comes from a darker shadow; on a light page it comes from a soft,
     slightly blue-tinted one. A neutral grey shadow on light looks dirty. */
  --shadow-sm: 0 1px 3px rgba(0, 0, 0, 0.35);
  --shadow-md: 0 4px 16px rgba(0, 0, 0, 0.4);
  --shadow-lg: 0 12px 32px rgba(0, 0, 0, 0.45);

  /* The sidebar rail is dark in BOTH modes — see SIDEBAR_SURFACE in
     theme.js. In dark mode it sits below the page; in light mode it becomes
     the navy chrome that makes the white cards read as floating. */
  /* Cards keep a hairline on dark (a shadow alone barely reads there) and
     drop it on light, where the shadow does the work and a border would
     make the card look pasted on. It's a token rather than a CSS override
     because four of the seven apps style their cards with INLINE style
     objects, which can't express "only in light mode". */
  --card-border: var(--line);

  /* Dark mode keeps its own, darker rail: the page here is #12161b, so a
     rail LIGHTER than the page would invert the intended depth — the rail
     recedes behind the content rather than floating above it. That caps how
     far this one can be lifted; #161d28 (the first attempt) overshot the
     page and the contrast test caught it. #101420 is the lightest value
     still below the page, and gains most of its change from being bluer
     (blue channel 0x16 → 0x20) rather than lighter, which is the part of
     "lighter blue" that dark mode can actually deliver. */
  --sidebar-bg: #101420;

  /* Categorical series for charts — distinguishable in order, and not
     reusing the semantic hues, so a chart series can never be mistaken for
     a status. */
  --series-1: #7c8cf8;
  --series-2: #4fc4cf;
  --series-3: #e8a33d;
  --series-4: #b98ee6;
  --series-5: #6ba5e7;
  --series-6: #d98a76;

  /* --- aliases: old names, new values -------------------------------- */

}

/* Light is the shipped default for new companies: staff read this on phones
   outdoors, where a dark UI loses badly to direct sun, and the Reports pages
   print far better from light. Dark stays a per-user toggle. */

/* ── Stat tiles ───────────────────────────────────────────────────────────
   A row of headline numbers reads as one undifferentiated block when the
   values just sit side by side — the eye has to work out where one metric
   ends and the next begins. Giving each its own inset tile does that work
   instead.

   Note ".kpi-row > div": the children are styled by POSITION rather than by
   class. That means converting a stat row is a one-line change to the
   wrapper, instead of adding a className to every number in seven apps —
   far fewer edits, and none of them can be half-done. Ops and Maintenance
   already use .kpi/.kpi-row markup, so they pick this up unchanged. */
.kpi-row {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  align-items: stretch;
}

.kpi-row > div,
.kpi {
  flex: 1 1 auto;
  min-width: 140px;
  background: var(--surface-overlay);
  border: 1px solid var(--card-border);
  border-radius: var(--radius-sm);
  padding: 12px 14px;
}

/* The tile sits on --surface-overlay, which on light is barely off-white and
   would leave the tile invisible against a white card. A hairline restores
   the edge without darkening the fill. */
:root[data-theme='light'] .kpi-row > div,
:root[data-theme='light'] .kpi {
  border-color: var(--line);
}
/* THEME-TOKENS-END */





  @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600&family=Inter:wght@300;400;500;600;700&display=swap');
  *{box-sizing:border-box;margin:0;padding:0}
  body{background:${T.bg};color:${T.cream};font-family:'Inter',sans-serif;min-height:100vh;-webkit-tap-highlight-color:transparent}
  .mono{font-family:'Inter',sans-serif;font-variant-numeric:tabular-nums}
  .shell{display:flex;height:100vh;overflow:hidden}
  .sidebar{width:230px;background:${T.panel};border-right:1px solid ${T.border};display:flex;flex-direction:column;flex-shrink:0}
  .main{flex:1;overflow-y:auto;background:${T.bg}}
  .bottom-nav{display:none}
  .logo{padding:18px 18px 12px;border-bottom:1px solid ${T.border};display:flex;flex-direction:column;align-items:center;gap:7px}
  .logo img{width:136px;height:auto;filter:brightness(0) invert(1) opacity(.9)}
  .logo-sub{font-size:9px;letter-spacing:.2em;text-transform:uppercase;color:${T.gold};font-weight:600;text-align:center}
  .loc-switcher{padding:10px 12px;border-bottom:1px solid ${T.border};display:flex;flex-direction:column;gap:3px}
  .loc-label{font-size:9px;letter-spacing:.16em;text-transform:uppercase;color:${T.muted};font-weight:600;margin-bottom:4px;padding-left:2px}
  .loc-btn{padding:7px 10px;border-radius:6px;border:1px solid transparent;font-family:'Inter',sans-serif;font-size:12px;font-weight:500;cursor:pointer;text-align:left;transition:all .15s;background:transparent;color:${T.muted};display:flex;align-items:center;gap:7px}
  .loc-btn:hover{color:${T.cream};background:rgba(255,255,255,.04)}
  .loc-btn.active-ZC{background:rgba(184,147,90,.15);border-color:rgba(184,147,90,.45);color:#B8935A}
  .loc-btn.active-EC{background:rgba(91,140,196,.15);border-color:rgba(91,140,196,.45);color:#5B8CC4}
  .loc-btn.active-SC{background:rgba(107,140,110,.15);border-color:rgba(107,140,110,.45);color:#7BAE7F}
  .loc-dot{display:inline-block;width:7px;height:7px;border-radius:50%;flex-shrink:0}
  .nav{flex:1;padding:6px 0;overflow-y:auto}
  .nav-section{font-size:9px;letter-spacing:.16em;text-transform:uppercase;color:${T.muted};padding:10px 16px 3px;font-weight:600;opacity:.7}
  .nav-item{display:flex;align-items:center;padding:8px 16px;cursor:pointer;font-size:13px;font-weight:500;color:${T.muted};transition:all .15s;border:none;background:none;width:100%;text-align:left}
  .nav-item:hover{color:${T.cream};background:rgba(184,147,90,.06)}
  .nav-item.active{color:${T.gold};background:rgba(184,147,90,.12);border-right:2px solid ${T.gold};font-weight:600}
  .topbar{background:${T.panel};border-bottom:1px solid ${T.border};padding:13px 26px;display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:10;gap:12px}
  .page-title{font-size:19px;font-weight:600;color:${T.cream};font-family:'Cormorant Garamond',serif;letter-spacing:.02em}
  .loc-badge{font-size:11px;font-weight:600;padding:4px 10px;border-radius:4px;letter-spacing:.04em;white-space:nowrap;cursor:pointer;border:none;display:flex;align-items:center;gap:5px;font-family:'Inter',sans-serif}
  .month-badge{background:rgba(184,147,90,.18);border:1px solid rgba(184,147,90,.45);color:${T.gold};font-size:11px;font-weight:600;padding:4px 12px;border-radius:4px;letter-spacing:.06em}
  .kpi-row{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;padding:20px 26px 0}
  .kpi{background:${T.panel};border:1px solid ${T.border};border-radius:8px;padding:14px 16px;position:relative;overflow:hidden}
  .kpi::before{content:'';position:absolute;top:0;left:0;right:0;height:3px;background:var(--accent,${T.gold})}
  .kpi-label{font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:${T.muted};font-weight:600;margin-bottom:5px}
  .kpi-value{font-size:21px;font-weight:700;color:${T.cream};font-family:'Inter',sans-serif}
  .kpi-sub{font-size:11px;color:${T.muted};margin-top:2px}
  .section{padding:20px 26px}
  .section-title{font-size:11px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:${T.gold};margin-bottom:10px;opacity:.9}
  .tbl-wrap{width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}
  .tbl{width:100%;border-collapse:collapse;font-size:13px;min-width:500px}
  .tbl th{text-align:left;font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:${T.muted};font-weight:600;padding:7px 10px;border-bottom:1px solid ${T.border};white-space:nowrap}
  .tbl td{padding:8px 10px;border-bottom:1px solid rgba(58,56,80,.5);color:${T.cream};vertical-align:middle}
  .tbl tr:hover td{background:rgba(184,147,90,.04)}
  .tbl .num{font-family:'Inter',sans-serif;text-align:right}
  .ok{color:${T.ok}} .bad{color:${T.danger}} .warn{color:${T.warn}}
  .badge{display:inline-block;font-size:10px;font-weight:700;padding:2px 8px;border-radius:3px;letter-spacing:.04em}
  .badge-ok{background:rgba(90,155,114,.18);color:${T.ok};border:1px solid rgba(90,155,114,.3)}
  .badge-warn{background:rgba(200,151,58,.18);color:${T.warn};border:1px solid rgba(200,151,58,.3)}
  .badge-bad{background:rgba(192,88,88,.18);color:${T.danger};border:1px solid rgba(192,88,88,.3)}
  .badge-neu{background:rgba(138,136,153,.15);color:${T.muted};border:1px solid rgba(138,136,153,.3)}
  .tabs{display:flex;border-bottom:1px solid ${T.border};margin-bottom:16px;overflow-x:auto}
  .tab{padding:8px 16px;font-size:12px;font-weight:600;cursor:pointer;border:none;background:none;color:${T.muted};border-bottom:2px solid transparent;transition:all .15s;white-space:nowrap;flex-shrink:0}
  .tab.active{color:${T.gold};border-bottom-color:${T.gold}}
  .tab:hover:not(.active){color:${T.cream}}
  .field{margin-bottom:12px}
  .field label{display:block;font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:${T.muted};font-weight:600;margin-bottom:4px}
  .field input,.field select,.field textarea{width:100%;background:rgba(0,0,0,.25);border:1px solid ${T.border};border-radius:6px;padding:10px 11px;color:${T.cream};font-family:'Inter',sans-serif;font-size:16px;outline:none;transition:border .15s}
  .field input:focus,.field select:focus,.field textarea:focus{border-color:${T.gold}}
  .field select option{background:${T.panel}}
  .field textarea{resize:vertical;font-size:14px}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:10px}
  .grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
  .btn{display:inline-flex;align-items:center;gap:6px;padding:9px 15px;border-radius:6px;font-family:'Inter',sans-serif;font-size:13px;font-weight:600;cursor:pointer;border:none;transition:all .15s}
  .btn-primary{background:${T.navy};color:${T.cream};border:1px solid ${T.navyLt}}
  .btn-primary:hover{background:${T.navyLt}}
  .btn-ghost{background:transparent;color:${T.muted};border:1px solid ${T.border}}
  .btn-ghost:hover{color:${T.cream};border-color:${T.muted}}
  .btn-danger{background:rgba(192,88,88,.15);color:${T.danger};border:1px solid rgba(192,88,88,.35)}
  .btn-sm{padding:4px 9px;font-size:11px}
  .overlay{position:fixed;inset:0;background:rgba(10,9,20,.85);z-index:200;display:flex;align-items:flex-end;justify-content:center;padding:0}
  .modal{background:${T.panel};border:1px solid ${T.border};border-radius:16px 16px 0 0;width:100%;max-width:560px;padding:22px 20px 36px;max-height:92vh;overflow-y:auto}
  .modal-title{font-size:18px;font-weight:600;color:${T.cream};margin-bottom:16px;display:flex;align-items:center;gap:8px;font-family:'Cormorant Garamond',serif}
  .modal-title span{color:${T.gold}}
  .strip{background:rgba(184,147,90,.06);border:1px solid rgba(184,147,90,.2);border-radius:8px;padding:11px 14px;display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin-bottom:16px}
  .strip-item{text-align:center;min-width:75px}
  .strip-label{font-size:9px;letter-spacing:.1em;text-transform:uppercase;color:${T.muted};font-weight:600}
  .strip-val{font-size:16px;font-weight:700;color:${T.gold};font-family:'Inter',sans-serif;margin-top:1px}
  .info-box{background:rgba(184,147,90,.08);border:1px solid rgba(184,147,90,.25);border-radius:6px;padding:8px 12px;display:flex;justify-content:space-between;align-items:center;margin-bottom:11px}
  .empty{padding:32px;text-align:center;color:${T.muted};font-size:13px}
  .count-input{width:90px;background:rgba(0,0,0,.3);border:1px solid ${T.border};border-radius:6px;padding:7px 10px;color:${T.cream};font-family:'Inter',sans-serif;font-size:14px;text-align:right;outline:none;transition:border .15s}
  .count-input:focus{border-color:${T.gold}}
  .reorder-qty{display:inline-block;background:rgba(192,88,88,.18);color:${T.danger};border:1px solid rgba(192,88,88,.3);border-radius:4px;font-family:'Inter',sans-serif;font-size:12px;font-weight:700;padding:2px 10px}
  .cal-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;margin-bottom:8px}
  .cal-head{font-size:9px;letter-spacing:.1em;text-transform:uppercase;color:${T.muted};font-weight:600;text-align:center;padding:5px 0}
  .cal-cell{background:${T.panel};border:1px solid ${T.border};border-radius:6px;min-height:88px;padding:5px 4px;display:flex;flex-direction:column;gap:3px}
  .cal-empty{background:transparent;border-color:transparent}
  .cal-today{border-color:${T.gold};box-shadow:0 0 0 1px rgba(184,147,90,.3)}
  .cal-drop-target{border-color:${T.ok};background:rgba(90,155,114,.1);box-shadow:0 0 0 1px rgba(90,155,114,.4)}
  .cal-job[draggable="true"]:active{opacity:.6}
  .cal-date{font-family:'Inter',sans-serif;font-size:11px;color:${T.muted};padding-left:3px}
  .cal-today .cal-date{color:${T.gold};font-weight:700}
  .cal-job{background:rgba(0,0,0,.28);border:none;border-radius:3px;padding:3px 5px;font-family:'Inter',sans-serif;font-size:10px;font-weight:500;text-align:left;cursor:pointer;line-height:1.3;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;width:100%}
  .cal-job:hover{background:rgba(184,147,90,.15)}
  .mobile-loc-bar{display:none}
  @media (max-width:768px){
    .sidebar{display:none}
    .bottom-nav{display:flex;position:fixed;bottom:0;left:0;right:0;background:${T.panel};border-top:1px solid ${T.border};z-index:100;padding:8px 12px;padding-bottom:calc(8px + env(safe-area-inset-bottom))}
    .nav-menu-btn{width:100%;display:flex;align-items:center;justify-content:center;gap:8px;padding:11px 14px;border-radius:10px;border:1px solid ${T.gold};background:rgba(184,147,90,.12);color:${T.goldLt};font-family:'Inter',sans-serif;font-weight:700;font-size:14px;cursor:pointer}
    .nav-overlay{position:fixed;inset:0;background:rgba(0,0,0,.55);display:flex;align-items:flex-end;justify-content:center;z-index:200}
    .nav-sheet{width:100%;max-width:560px;max-height:75vh;overflow-y:auto;background:${T.panel};border:1px solid ${T.border};border-bottom:none;border-radius:16px 16px 0 0}
    .nav-sheet-header{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;border-bottom:1px solid ${T.border};position:sticky;top:0;background:${T.panel}}
    .nav-sheet-title{font-family:'Cormorant Garamond',serif;font-size:18px;font-weight:600;color:${T.goldLt}}
    .nav-sheet-close{padding:5px 12px;border-radius:8px;border:1px solid ${T.border};background:transparent;color:${T.cream};font-family:'Inter',sans-serif;font-size:13px;cursor:pointer}
    .nav-sheet-item{display:block;width:100%;text-align:left;padding:14px 16px;border:none;border-bottom:1px solid ${T.border};background:none;color:${T.cream};font-family:'Inter',sans-serif;font-weight:500;font-size:14px;cursor:pointer}
    .nav-sheet-item.active{background:rgba(184,147,90,.12);color:${T.goldLt};font-weight:700}
    .main{padding-bottom:76px}
    .topbar{padding:9px 14px}
    .page-title{font-size:15px}
    .month-badge,.loc-badge{font-size:10px;padding:3px 8px}
    .mobile-loc-bar{display:flex;gap:5px;padding:7px 12px;background:${T.panel};border-bottom:1px solid ${T.border};overflow-x:auto;-webkit-overflow-scrolling:touch}
    .mobile-loc-btn{flex-shrink:0;padding:5px 11px;border-radius:20px;border:1px solid transparent;font-family:'Inter',sans-serif;font-size:11px;font-weight:600;cursor:pointer;background:transparent;color:${T.muted};display:flex;align-items:center;gap:5px;white-space:nowrap}
    .mobile-loc-btn.active-ZC{background:rgba(184,147,90,.18);border-color:rgba(184,147,90,.5);color:#B8935A}
    .mobile-loc-btn.active-EC{background:rgba(91,140,196,.18);border-color:rgba(91,140,196,.5);color:#5B8CC4}
    .mobile-loc-btn.active-SC{background:rgba(107,140,110,.18);border-color:rgba(107,140,110,.5);color:#7BAE7F}
    .section{padding:12px 14px}
    .kpi-row{grid-template-columns:1fr 1fr;gap:9px;padding:12px 14px 0}
    .kpi-value{font-size:17px}
    .grid2,.grid3{grid-template-columns:1fr}
    .count-input{width:75px}
    .cal-cell{min-height:62px;padding:3px 2px}
    .cal-job{font-size:8px;padding:2px 3px}
    .cal-grid{gap:2px}
  }
  @media (min-width:769px){.mobile-loc-bar{display:none!important}.nav-overlay{display:none!important}}
  ::-webkit-scrollbar{width:4px;height:4px}
  ::-webkit-scrollbar-thumb{background:${T.border};border-radius:3px}


  /* ── Elevation + dark rail (2026-09-06) ────────────────────────────────
     Appended last so it wins over the earlier .sidebar rules without
     !important. The rail is dark in BOTH modes: against a light page that
     navy is what makes the cards read as floating, and it keeps the app's
     silhouette constant while a client accent changes only the highlights.
     Its text colours are fixed tokens, never --cream/--muted, because those
     flip with the mode and would turn near-black on navy in light mode. */
  .sidebar{background:var(--sidebar-bg);color:var(--sidebar-text);border-right:1px solid var(--sidebar-line)}
  .sidebar-logo{border-bottom-color:var(--sidebar-line)}
  .sidebar-sub{color:var(--accent-on-dark)}
  .sidebar-company{color:var(--sidebar-muted)}
  .sidebar-select-wrap{border-bottom-color:var(--sidebar-line)}
  .sidebar-select{border-color:var(--sidebar-line);color:var(--sidebar-text);border-radius:var(--radius-sm)}
  .sidebar-select option{background:var(--sidebar-bg);color:var(--sidebar-text)}
  .nav{padding:8px 10px}
  .nav-item{color:var(--sidebar-muted);border-right:none;border-radius:var(--radius-sm);padding:9px 12px}
  .nav-item:hover{color:var(--sidebar-text);background:rgba(255,255,255,.06)}
  .nav-item.active{color:var(--accent-on-dark);background:var(--accent-on-dark-wash);border-right:none}
  .sidebar-footer{border-top-color:var(--sidebar-line);color:var(--sidebar-muted)}
  .sidebar-footer-btn{color:var(--sidebar-muted)}
  .role-badge{border-color:var(--sidebar-line);color:var(--sidebar-muted)}
  .bottom-nav,.nav-sheet{background:var(--sidebar-bg);color:var(--sidebar-text)}
  .nav-sheet-item.active{color:var(--accent-on-dark);background:var(--accent-on-dark-wash)}

  /* Cards lift off the page instead of being outlined on it. */
  .card,.panel{background:var(--surface-raised);border:1px solid var(--card-border);border-radius:var(--radius-md);box-shadow:var(--shadow-md)}
`;
